GET http://localhost:3000
###
GET http://localhost:3000/items
###
POST http://localhost:3000/items
Content-Type: application/json

  {  
    "title": "Camara Digital Canon EOS M50",
    "price": 850,
    "image": "camara-canon-eos.jpg"
    }


###
POST http://localhost:3000/order
Content-Type: application/json

{
  "items": [
    {
      "qty": 5
    }
  ]
}

###
GET http://localhost:3000/items/item
Content-Type: application/json
{

  "itemId": "6176ddbe4a2aa83e39405e73"
}
###
GET http://localhost:3000/items/item
Content-Type: application/json

{
    "itemId":"6176ddbe4a2aa83e39405e73"
}
###
POST http://localhost:3000/create-payment-intent
Content-Type: application/json

[
  {
    "id":"6176ddbe4a2aa83e39405e73",
    "qty": 2
  }
]